### ISSUE TITLE
Incorrect reversal of "noël"

### ISSUE THREAD

**Issue by nathanl** [mathiasbynens/esrever#10]
`esrever.reverse("noël")` returns `"l̈eon"`. It should return `"lëon"`.

(From https://mortoray.com/2013/11/27/the-string-type-is-broken/)

**Comment by mathiasbynens** [comment]
I cannot confirm this issue. https://mothereff.in/reverse-string#noe%CC%88l also shows the correct result. Care to elaborate?

**Comment by nathanl** [comment]
@mathiasbynens Sorry. I may not know How To Javascript™. 😆 When I use node to run it from the command line as you show, I get the correct result.

What I tried before was to go [to your source](https://raw.githubusercontent.com/mathiasbynens/esrever/48e1f4587169d54a57f4bb4693d8ee1ea5b012f5/src/esrever.js) in Chrome (Version 51.0.2704.103 (64-bit)), copy-paste the code into the console so that `esrever` would be defined, and try it from there. In that case, it looks wrong.

<img width="1438" alt="wrong_reversal_in_console" src="https://cloud.githubusercontent.com/assets/338814/16519340/2b4f47fc-3f56-11e6-96ab-1e5af3917f73.png">

You probably have better things to do, but if you feel like taking time to tell me why that doesn't/shouldn't work, I'd appreciate it.

Either way, sorry to bother you with an invalid bug report.

**Comment by mathiasbynens** [comment]
That’s the uncompiled source, not the actual source code. The `<%= %>` give it away. [`src/esrever.js`](https://github.com/mathiasbynens/esrever/blob/master/src/esrever.js) is used as a template to generate [`esrever.js`](https://github.com/mathiasbynens/esrever/blob/master/esrever.js) at build time.

**Comment by mathiasbynens** [comment]
I could probably make that clearer by renaming `src/esrever.js` to something like `src/esrever.js.tpl` but then again I don’t wanna lose syntax highlighting…

**Comment by nathanl** [comment]
Ah, thanks for clarifying! BTW - after posting this I came across some of your articles on Unicode support in Javascript. Excellent work! 👍
