### ISSUE TITLE
Manana example appears broken in Firefox

### ISSUE THREAD

**Issue by paulkogel** [mathiasbynens/esrever#11]
In Firefox 48.0.1 on OSX the manana example appears like this for me:
![](https://monosnap.com/file/JFKnBbjxF9lHz6lDuVkmezT7FblMTl.png)

was wondering what "so now the tilde is applied to the `a` instead of the `n`" was referring to until I checked it out in Chrome. Not sure if this is a known problem!?

**Comment by mathiasbynens** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1107568

**Comment by paulkogel** [comment]
Thanks for the link. I had an old version of the Microsoft font Consolas installed (1.00 from 2005, current version is >=5.32).
Fixed by uninstalling the font, could also have updated it.
Github's font stack has Consolas as its first monotype font before OSX fonts like Menlo.

**Comment by mathiasbynens** [comment]
Nice find — thanks for the info!
